import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Gamepad2 } from "lucide-react";
import { games } from "@/data/games";
import { SiteShell, PageHeader } from "@/components/layout/SiteShell";

export const metadata: Metadata = { title: "เกมทั้งหมด" };

export default function GamesPage() {
  return <SiteShell><PageHeader eyebrow="Game directory" title="เลือกเกมของคุณ" description="รวมเกมยอดนิยมและสินค้า Digital ที่พร้อมส่งทันที เลือกเกมเพื่อดู Points, Skins, Pass และ Bundle ทั้งหมด" /><section className="container-page py-14"><div className="mb-8 flex items-center justify-between"><p className="text-sm text-slate-400">พบ <strong className="text-white">{games.length}</strong> หมวดเกม</p><Link href="/shop" className="text-sm font-bold text-cyan">ดูสินค้าทั้งหมด</Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{games.map((game, index) => <Link href={`/shop?game=${game.slug}`} key={game.slug} className="group relative min-h-64 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900 transition hover:-translate-y-1 hover:border-cyan/50 hover:shadow-glow"><div className={`absolute inset-0 bg-gradient-to-br ${game.gradient}`} /><div className="cyber-noise absolute inset-0 opacity-20" /><span className="absolute right-6 top-5 text-7xl font-black text-white/10">{game.mark}</span>{index === 0 && <span className="absolute left-5 top-5 rounded-full bg-cyan px-3 py-1 text-[9px] font-black text-slate-950">แนะนำ</span>}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black via-black/70 to-transparent p-6 pt-20"><p className="text-xs text-cyan">{game.shortName}</p><h2 className="mt-1 text-xl font-black text-white">{game.name}</h2><div className="mt-4 flex items-center justify-between"><span className="text-xs text-slate-400">{game.productCount} สินค้า</span><span className="flex items-center gap-1 text-xs font-bold text-white">ดูสินค้า <ArrowRight size={14} /></span></div></div></Link>)}</div><div className="mt-10 flex flex-col items-center rounded-2xl border border-dashed border-slate-700 bg-slate-900/30 p-10 text-center"><Gamepad2 className="text-blue-400" size={32} /><h2 className="mt-4 font-bold">หาเกมที่ต้องการไม่เจอ?</h2><p className="mt-2 text-sm text-slate-500">ส่งชื่อเกมให้ทีม LootBerry เราจะช่วยค้นหาสินค้าให้คุณ</p><button className="button-secondary mt-5">ติดต่อทีมงาน</button></div></section></SiteShell>;
}
